The-Standard-Organization/GitFyle.Core.Api

.gitignore
GitFyle.Core.Api/GitFyle.Core.Api.sln
GitFyle.Core.Api/GitFyle.Core.Api/Controllers/HomeController.cs
GitFyle.Core.Api/GitFyle.Core.Api/GitFyle.Core.Api.csproj
GitFyle.Core.Api/GitFyle.Core.Api/GitFyle.Core.Api.http
GitFyle.Core.Api/GitFyle.Core.Api/Program.cs
GitFyle.Core.Api/GitFyle.Core.Api/Properties/launchSettings.json
GitFyle.Core.Api/GitFyle.Core.Api/appsettings.json

INFRA: Initialize API Project

---

GitFyle.Core.Api/.github/workflows/build.yml
GitFyle.Core.Api/GitFyle.Core.Api.sln
GitFyle.Core.Api/GitFyle.Core.Infrastructure/GitFyle.Core.Infrastructure.csproj
GitFyle.Core.Api/GitFyle.Core.Infrastructure/Program.cs
GitFyle.Core.Api/GitFyle.Core.Infrastructure/Services/ScriptGenerationService.cs

INFRA: Build Script

---

GitFyle.Core.Api.Tests.Unit/DeletMe.cs
GitFyle.Core.Api.Tests.Unit/GitFyle.Core.Api.Tests.Unit.csproj
GitFyle.Core.Api.sln
GitFyle.Core.Api/GitFyle.Core.Api.csproj
GitFyle.Core.Infrastructure/GitFyle.Core.Infrastructure.csproj
GitFyle.Core.Infrastructure/Services/ScriptGenerationService.cs

INFRA: Initialize Unit Tests

---

GitFyle.Core.Api.Tests.Acceptance/DeleteMe.cs
GitFyle.Core.Api.Tests.Acceptance/GitFyle.Core.Api.Tests.Acceptance.csproj
GitFyle.Core.Api.Tests.Unit/DeleteMe.cs
GitFyle.Core.Api.sln

INFRA: Initialise Acceptance Proj

---

GitFyle.Core.Api/Brokers/DateTimes/DateTimeBroker.cs
GitFyle.Core.Api/Brokers/DateTimes/IDateTimeBroker.cs
GitFyle.Core.Api/Program.cs

closes #26 
- Added DateTime Broker and GetCurrentDateTime method

BROKERS: Initialize DateTime Broker

---

GitFyle.Core.Api/Brokers/Loggings/ILoggingBroker.cs
GitFyle.Core.Api/Brokers/Loggings/LoggingBroker.cs

BROKERS: loggingBroker-LogError

---

GitFyle.Core.Api/Brokers/Loggings/ILoggingBroker.cs
GitFyle.Core.Api/Brokers/Loggings/LoggingBroker.cs

BROKERS: LoggingBroker - LogCritical

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Sources.cs
GitFyle.Core.Api/Brokers/Storages/IStorageBroker.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Sources.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Insert Source

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Sources.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Sources.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Source-deleteSourceAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Repositories.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Contributor - SelectContributorByIdAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.cs

BROKERS: Contributor - DeleteContributorAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributors.cs

BROKERS: Contributor - UpdateContributorAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributors.cs

BROKERS: Contributor - InsertContributorAsync 

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.ContributionType.cs

BROKERS: Insert ContributionType

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributions.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributions.cs

BROKERS: Insert Contribution

---

GitFyle.Core.Api/GitFyle.Core.Api.http

INFRA: Set HTTP Uses HomeController

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.ContributionTypes.cs
GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributions.cs
GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Repositories.cs
GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Sources.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.ContributionTypes.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributions.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Contributors.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Repositories.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Sources.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.cs

Updated SelectAll methods from the IStorageBroker/StorageBroker to be asychronous in adherence to the changes made in "The Standard" v2.10.3

CODE RUB: Update Brokers v2.10.3

---

GitFyle.Core.Api/Migrations/20240729173709_UpdatedExternalAuditPropertiesForRepositoryContributorContribution.Designer.cs
GitFyle.Core.Api/Migrations/20240729173709_UpdatedExternalAuditPropertiesForRepositoryContributorContribution.cs
GitFyle.Core.Api/Models/Foundations/Contributions/Contribution.cs
GitFyle.Core.Api/Models/Foundations/Contributors/Contributor.cs
GitFyle.Core.Api/Models/Foundations/Repositories/Repository.cs
Resources/Diagrams/GitFyle.drawio

CODE RUB:  Updated draw.io file with new Configuration table and audit properties on Source and ContributionType

---

README.md

DOCUMENTATION: Readme V2.10.3

---

GitFyle.Core.Api/Brokers/DateTimes/DateTimeBroker.cs
GitFyle.Core.Api/Brokers/DateTimes/IDateTimeBroker.cs
GitFyle.Core.Api/Brokers/Loggings/ILoggingBroker.cs
GitFyle.Core.Api/Brokers/Loggings/LoggingBroker.cs
GitFyle.Core.Api/GitFyle.Core.Api.csproj

BROKERS: Support Brokers Upgrade v2.10.3

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Configurations.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Configurations.cs

BROKERS: Configuration - SelectAllConfigurationsAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Configurations.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Configurations.cs

BROKERS: Configuration - SelectConfigurationByIdAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Configurations.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Configurations.cs

BROKERS: Configuration - UpdateConfigurationAsync

---

GitFyle.Core.Api/Brokers/Storages/IStorageBroker.Configurations.cs
GitFyle.Core.Api/Brokers/Storages/StorageBroker.Configurations.cs

BROKERS: Configuration - DeleteConfigurationAsync 

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Validations.Add.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Validations.cs

FOUNDATIONS: Source Service - Max length validation

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Exceptions.RetrieveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Logic.RetrieveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Validations.RetrieveById.cs
GitFyle.Core.Api/Models/Foundations/Sources/Exceptions/NotFoundSourceException.cs
GitFyle.Core.Api/Services/Foundations/Sources/ISourceService.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.cs

FOUNDATIONS: Source - `RetrieveByIdAsync`

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Exceptions.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Logic.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.cs
GitFyle.Core.Api/Services/Foundations/Sources/ISourceService.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.cs

FOUNDATIONS: Source - `RetrieveAllAsync`

---

GitFyle.Core.Api/Controllers/SourcesController.cs
GitFyle.Core.Api/GitFyle.Core.Api.csproj
GitFyle.Core.Api/Services/Foundations/Sources/ISourceService.cs

CONTROLLERS: Post Source

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Exceptions.Add.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Exceptions.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Logic.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Validations.Add.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Exceptions.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Sources/SourceServiceTests.Validations.RemoveById.cs
GitFyle.Core.Api/Services/Foundations/Configurations/ConfigurationService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Configurations/ConfigurationService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Configurations/ConfigurationService.cs
GitFyle.Core.Api/Services/Foundations/Configurations/IConfigurationService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/IContributionService.cs

FOUNDATIONS: Configuration - RetrieveAllConfigurationsAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Exceptions.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Logic.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/IContributionService.cs

FOUNDATIONS: Contribution-RetrieveAllAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Exceptions.RetrieveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Logic.RetrieveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Validations.RetrieveById.cs
GitFyle.Core.Api/Models/Foundations/Contributions/Exceptions/NotFoundContributionException.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/IContributionService.cs

FOUNDATIONS: Contribution-RetrieveByIdAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Exceptions.Add.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Exceptions.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Exceptions.RetrieveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Logic.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.Validations.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Configurations/ConfigurationServiceTests.cs
GitFyle.Core.Api/Models/Foundations/Configurations/Exceptions/LockedConfigurationException.cs
GitFyle.Core.Api/Models/Foundations/Configurations/Exceptions/NotFoundConfigurationException.cs
GitFyle.Core.Api/Services/Foundations/Configurations/ConfigurationService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Configurations/ConfigurationService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Configurations/ConfigurationService.cs
GitFyle.Core.Api/Services/Foundations/Configurations/IConfigurationService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/IContributionService.cs
GitFyle.Core.Api/Services/Foundations/Sources/SourceService.Exceptions.cs

FOUNDATIONS: Configuration - ModifyAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Exceptions.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Logic.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.Validations.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributions/ContributionServiceTests.cs
GitFyle.Core.Api/Models/Foundations/Contributions/Exceptions/LockedContributionException.cs
GitFyle.Core.Api/Models/Foundations/Contributions/Exceptions/NotFoundContributionException.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.cs
GitFyle.Core.Api/Services/Foundations/Contributions/IContributionService.cs

FOUNDATIONS: Contribution-ModifyAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.Add.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Logic.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Validations.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.cs
GitFyle.Core.Api/Models/Foundations/Repositories/Exceptions/LockedRepositoryException.cs
GitFyle.Core.Api/Services/Foundations/Repositories/IRepositoryService.cs
GitFyle.Core.Api/Services/Foundations/Repositories/RepositoryService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Repositories/RepositoryService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Repositories/RepositoryService.cs

FOUNDATIONS: Repository-ModifyAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Logic.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Validations.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Validations.RemoveById.cs
GitFyle.Core.Api/Services/Foundations/Repositories/IRepositoryService.cs
GitFyle.Core.Api/Services/Foundations/Repositories/RepositoryService.cs

FOUNDATIONS: Repository RemoveByIdAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Exceptions.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Logic.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Validations.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Validations.Modify.cs
GitFyle.Core.Api/Models/Foundations/ContributionTypes/Exceptions/LockedContributionTypeException.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/ContributionTypeService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/ContributionTypeService.Validations.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/ContributionTypeService.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/IContributionTypeService.cs

FOUNDATIONS: ContributionType-ModifyAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Exceptions.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Logic.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Validations.RemoveById.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/ContributionTypeService.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/IContributionTypeService.cs

FOUNDATIONS: ContributionType-RemoveByIdAsync

---

GitFyle.Core.Api.Tests.Unit/Controllers/Configurations/ConfigurationsControllerTests.Exceptions.Put.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Configurations/ConfigurationsControllerTests.Logic.Put.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/ContributionTypes/ContributionTypeServiceTests.Logic.RetrieveAll.cs
GitFyle.Core.Api/Controllers/ConfigurationsController.cs
GitFyle.Core.Api/Models/Foundations/ContributionTypes/Exceptions/ContributionTypeDependencyValidationException.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/ContributionTypeService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/ContributionTypeService.Validations.cs
GitFyle.Core.Api/Services/Foundations/ContributionTypes/IContributionTypeService.cs

CONTROLLERS: Configurations - PutConfigurationAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Exceptions.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Logic.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.cs
GitFyle.Core.Api/Services/Foundations/Contributors/IContributorService.cs

FOUNDATIONS: Contributor RetrieveAllAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Exceptions.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Logic.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Validations.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.Exceptions.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.cs
GitFyle.Core.Api/Services/Foundations/Contributors/IContributorService.cs

FOUNDATIONS: Contributor ModifyAsync

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Exceptions.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Logic.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Validations.RemoveById.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.cs
GitFyle.Core.Api/Services/Foundations/Contributors/IContributorService.cs

FOUNDATIONS: Contributor RemoveByIdAsync

---

GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Exceptions.Get.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Logic.Get.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.cs
GitFyle.Core.Api/Controllers/RepositoriesController.cs

CONTROLLERS: Repository Controller - Get

---

GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Exceptions.GetById.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Logic.GetById.cs
GitFyle.Core.Api/Controllers/RepositoriesController.cs

CONTROLLERS: Repository Controller - GetById

---

GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Exceptions.Delete.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Logic.Delete.cs
GitFyle.Core.Api/Controllers/RepositoriesController.cs

CONTROLLERS: Repository Controller - Delete

---

GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Exceptions.Put.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Logic.Put.cs
GitFyle.Core.Api/Controllers/RepositoriesController.cs

CONTROLLERS: Repository Controller - Put

---

GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Exceptions.Post.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Repositories/RepositoriesControllerTests.Logic.Post.cs
GitFyle.Core.Api/Controllers/RepositoriesController.cs

CONTROLLERS: Repository Controller - Post

---

GitFyle.Core.Api.Tests.Unit/Controllers/Sources/SourcesControllerTests.Exception.Get.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Sources/SourcesControllerTests.Logic.Get.cs
GitFyle.Core.Api/Controllers/SourcesController.cs

* This PR just fixes a few issues especially the controller method name

CODE RUB: Fix Controller Method Name

---

GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Exceptions.GetAll.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Logic.GetAll.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.cs
GitFyle.Core.Api/Controllers/ContributionsController.cs

* This PR is ready for review. Closes #235 
* Next step is to push forward with the other CRUD controller endpoints

CONTROLLERS: `GET` All Contributions

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Sources.cs

ACCEPTANCE: Post Source

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Configurations.cs
GitFyle.Core.Api.Tests.Acceptance/Models/Configurations/Configuration.cs

CODE RUB: Acceptance Configuration Add Models

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Configurations.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Sources.cs

ACCEPTANCE: PUT Configuration

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Configurations.cs

ACCEPTANCE: Delete Configuration

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Sources.cs
GitFyle.Core.Api.Tests.Acceptance/Models/Configurations/Configuration.cs
GitFyle.Core.Api.Tests.Acceptance/Models/Sources/Source.cs

CODE RUB: Acceptance Source Add Models

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Sources.cs

ACCEPTANCE: GET Sources

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.Logic.cs
GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.cs
GitFyle.Core.Api.Tests.Acceptance/Brokers/GitFyleCoreApiBroker.Sources.cs

ACCEPTANCE: PUT Source

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Sources/SourcesApiTests.Logic.cs

ACCEPTANCE: Delete Source By Id

---

GitFyle.Core.Api.Tests.Acceptance/Apis/Configurations/ConfigurationsApiTests.Logic.cs

ACCEPTANCE: GET Configuration By Id

---

GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.Validations.cs
GitFyle.Core.Api/Services/Foundations/Contributions/ContributionService.cs

MINOR CODE RUB: Reverts Contribution ValueTask Abstraction v2.10.3

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.Add.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.Modify.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.RemoveById.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.RetrieveAll.cs
GitFyle.Core.Api.Tests.Unit/Services/Foundations/Repositories/RepositoryServiceTests.Exceptions.RetrieveById.cs
GitFyle.Core.Api/Services/Foundations/Repositories/RepositoryService.Exceptions.cs

MINOR CODE RUB: Repository Service Exceptions Variable Names Fix

---

GitFyle.Core.Api/Services/Foundations/Repositories/RepositoryService.Validations.cs

MINOR CODE RUB: Repository Service Validations Method Naming Fix

---

GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Exception.GetById.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Exceptions.Put.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Logic.Put.cs
GitFyle.Core.Api/Controllers/ContributionsController.cs

MEDIUM CONTROLLERS: Contribution Put Tests

---

GitFyle.Core.Api/Controllers/SourcesController.cs

MINOR CODE RUB: Source Controller Format Fix

---

GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Exceptions.Delete.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.Logic.Delete.cs
GitFyle.Core.Api.Tests.Unit/Controllers/Contributions/ContributionsControllerTests.cs
GitFyle.Core.Api/Controllers/ContributionsController.cs

MAJOR CONTROLLERS: Contribution Delete Tests

---

README.md

DOCUMENTATION: Update 2.11.1 Controller Testing

---

GitFyle.Core.Api.Tests.Unit/Controllers/ContributionTypes/ContributionTypesControllerTests.Exceptions.Put.cs
GitFyle.Core.Api/Controllers/ContributionTypesController.cs

CODERUB: ContributionType Put Tests

---

GitFyle.Core.Api.Tests.Unit/Services/Foundations/Contributors/ContributorServiceTests.Exceptions.Add.cs
GitFyle.Core.Api/Models/Foundations/Contributors/Exceptions/InvalidReferenceContributorException.cs
GitFyle.Core.Api/Services/Foundations/Contributors/ContributorService.Exceptions.cs

MINOR FOUNDATIONS: Add Contributor => Source FK Test
